changed pipeline to run all tests and publish test results, but fail in the end on test failure; also uploading logs on failure; also made sure that failing test execution will result in a red status on testspace; added an internal timeout to cucumber tests

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -143,25 +143,39 @@ jobs:
         run: |
           docker push metasfresh/metas-frontend:${{ needs.init.outputs.tag-fixed }}
           docker push metasfresh/metas-frontend:${{ needs.init.outputs.tag-floating }}
-      - name: extract-test-results
-        run: |
-          docker buildx build \
-          -f docker-builds/Dockerfile.frontend \
-          --target testresults \
-          -t metas-frontend:testresults \
-          .
-          docker cp "$(docker create --name temp metas-frontend:testresults):/results" . && docker rm temp
-      - uses: testspace-com/setup-testspace@v1
-        with:
-          domain: metasfresh
-      - name: push-results
-        run: |
-          testspace "[jest/frontend]results/junit.xml" "[jest/frontend]results/test.log"
       - name: produce-summary
-        # echo '* metasfresh/metas-mobile:${{ needs.init.outputs.tag-fixed }}' >> $GITHUB_STEP_SUMMARY
+          # echo '* metasfresh/metas-mobile:${{ needs.init.outputs.tag-fixed }}' >> $GITHUB_STEP_SUMMARY
         run: |
           echo '#### images' >> $GITHUB_STEP_SUMMARY
           echo '* metasfresh/metas-frontend:${{ needs.init.outputs.tag-fixed }}' >> $GITHUB_STEP_SUMMARY
+          
+  test-frontend:
+    name: test (frontend)
+    runs-on: ubuntu-latest
+    needs: [init, frontend]
+    steps:
+      - uses: actions/checkout@v3
+      - uses: testspace-com/setup-testspace@v1
+        with:
+          domain: metasfresh
+      - name: run-tests
+        run: |
+          docker buildx build \
+          -f docker-builds/Dockerfile.frontend \
+          --target test \
+          -t metas-frontend:test \
+          .
+      - name: publish results
+        run: |
+          docker run --rm -v "$(pwd)/jest:/reports" metas-frontend:test                                             # extracting test results from docker image
+          find jest -type d -links 2 -exec testspace [{}]{}/*.xml \;                                                # upload all jest xml's to testspace 
+          testspace "[jest/frontend]jest/frontend/jest.log{$(cat jest/frontend/jest.exit-code):webui jest tests}"   # upload webui log with exit code
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: jest-logs
+          path: jest/**/jest.log
+
   backend:
     runs-on: ubuntu-latest
     needs: [init, java]
@@ -324,15 +338,18 @@ jobs:
           echo '* metasfresh/metasfresh-webui:${{ needs.init.outputs.tag-fixed }}-compat' >> $GITHUB_STEP_SUMMARY
 
   junit:
+    name: test (java)
     runs-on: ubuntu-latest
     needs: [init, java]
-    continue-on-error: true
     steps:
       - uses: actions/checkout@v3
       - uses: docker/login-action@v2
         with:
           username: metasfresh
           password: ${{ secrets.DOCKERHUB_METASFRESH_RW_TOKEN }}
+      - uses: testspace-com/setup-testspace@v1
+        with:
+          domain: metasfresh
       - name: run-junit-tests-j8
         run: |
           docker buildx build \
@@ -341,6 +358,7 @@ jobs:
           --cache-from metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }} \
           --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
           -t metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }} \
+          -t metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }} \
           .
       - name: run-junit-tests-j14
         run: |
@@ -350,36 +368,47 @@ jobs:
           --cache-from metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}-j14 \
           --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
           -t metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}-j14 \
+          -t metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }}-j14 \
           .
       - name: push-result-image
         run: |
           docker push metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}
           docker push metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}-j14
-      - uses: testspace-com/setup-testspace@v1
-        with:
-          domain: metasfresh
       - name: push-results
-        env:
-          runurl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         run: |
-          docker run --rm -v "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}
-          docker run --rm -v "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-floating }}-j14
-          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;
+          docker run --rm -v "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }}                 # extracting java8 test results from docker image
+          docker run --rm -v "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }}-j14             # extracting java14 test results from docker image
+          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;                                                           # upload all junit xml's to testspace 
+          testspace "[junit/commons]junit/commons/junit.log{$(cat junit/commons/junit.exit-code):java 8 commons junit tests}"   # upload commons log with exit code 
+          testspace "[junit/backend]junit/backend/junit.log{$(cat junit/backend/junit.exit-code):java 8 backend junit tests}"   # upload backend log with exit code
+          testspace "[junit/camel]junit/camel/junit.log{$(cat junit/camel/junit.exit-code):jav 14 camel junit tests}"           # upload camel log with exit code      
+      - name: assert success
+        run: |
+          if [ $(cat junit/commons/junit.exit-code) != 0 ] || [ $(cat junit/commons/junit.mvn.exit-code) != 0 ]; then cat junit/commons/junit.log && exit 1; fi      # print commons log and exit if commons failed
+          if [ $(cat junit/backend/junit.exit-code) != 0 ] || [ $(cat junit/backend/junit.mvn.exit-code) != 0 ]; then cat junit/backend/junit.log && exit 1; fi      # print backend log and exit if backend failed
+          if [ $(cat junit/camel/junit.exit-code) != 0 ] || [ $(cat junit/camel/junit.mvn.exit-code) != 0 ]; then cat junit/camel/junit.log && exit 1; fi            # print camel log and exit if camel failed
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: junit-logs
+          path: junit/**/junit.log
       - name: produce-summary
         run: |
           echo 'test results can be found at https://metasfresh.testspace.com/' >> $GITHUB_STEP_SUMMARY
 
-
   cucumber:
+    name: test (cucumber)
     runs-on: ubuntu-latest
     needs: [init, backend, frontend]
-    continue-on-error: true
     steps:
       - uses: actions/checkout@v3
       - uses: docker/login-action@v2
         with:
           username: metasfresh
           password: ${{ secrets.DOCKERHUB_METASFRESH_RW_TOKEN }}
+      - uses: testspace-com/setup-testspace@v1
+        with:
+          domain: metasfresh
       - name: build-cucumber
         run: |
           docker buildx build \
@@ -399,16 +428,20 @@ jobs:
         run: |
           mkdir cucumber
           docker cp "$(docker create --name tempcopytainer metasfresh/metas-cucumber:$refname):/compose.yml" . && docker rm tempcopytainer
-          docker-compose up --abort-on-container-exit --exit-code-from cucumber
+          docker-compose up --abort-on-container-exit --exit-code-from cucumber 2>&1 | tee cucumber.log && echo "${PIPESTATUS[0]}" > cucumber.exit-code
           docker-compose down
-      - uses: testspace-com/setup-testspace@v1
-        with:
-          domain: metasfresh
       - name: push-results
-        env:
-          runurl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         run: |
-          find cucumber -type d -links 2 -exec testspace [{}]{}/*.xml \;
+          find cucumber -type d -links 2 -exec testspace [{}]{}/*.xml \;                    # upload all cucumber xml's to testspace
+          testspace "[cucumber]cucumber.log{$(cat cucumber.exit-code):cucumber tests}"      # upload cucumber log with exit code 
+      - name: assert success
+        run: |
+          if [ $(cat cucumber.exit-code) != 0 ]; then cat cucumber.log && exit 1; fi        # print cucumber log and exit if cucumber failed
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: cucumber-logs
+          path: cucumber.log
       - name: produce-summary
         run: |
           echo 'test results can be found at https://metasfresh.testspace.com/' >> $GITHUB_STEP_SUMMARY
