fix db version mismatch and disable mobile healthCheck

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -1,7 +1,7 @@
 name: cicd
 on: [push, workflow_dispatch]
 env:
-  PIPELINE_VERSION: '0.3.4'
+  PIPELINE_VERSION: '0.3.5'
 jobs:
 
   init:
@@ -646,11 +646,11 @@ jobs:
         if: success() || failure()
         run: |
           ./containerHealthCheck.sh webui
-      - name: mobile health check
-        working-directory: docker-builds/health/
-        if: success() || failure()
-        run: |
-          ./containerHealthCheck.sh mobile
+#      - name: mobile health check
+#        working-directory: docker-builds/health/
+#        if: success() || failure()
+#        run: |
+#          ./containerHealthCheck.sh mobile
 #      - name: run api health checks
 #        working-directory: docker-builds/health/
 #        if: success() || failure()
@@ -667,7 +667,7 @@ jobs:
           docker inspect --format "{{json .State.Health }}" compose_rabbitmq_1 | jq
           docker inspect --format "{{json .State.Health }}" compose_search_1 | jq
           docker inspect --format "{{json .State.Health }}" compose_webui_1 | jq
-          docker inspect --format "{{json .State.Health }}" compose_mobile_1 | jq
+#          docker inspect --format "{{json .State.Health }}" compose_mobile_1 | jq
           docker inspect --format "{{json .State.Health }}" compose_external_1 | jq
       - name: stop docker-compose
         working-directory: docker-builds/compose/
