added missing assertion for frontend jest tests; made sure that mvn failures also result in red status on testspace

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -170,6 +170,9 @@ jobs:
           docker run --rm --volume "$(pwd)/jest:/reports" metas-frontend:test                                       # extracting test results from docker image
           find jest -type d -links 2 -exec testspace [{}]{}/*.xml \;                                                # upload all jest xml's to testspace 
           testspace "[jest/frontend]jest/frontend/jest.log{$(cat jest/frontend/jest.exit-code):webui jest tests}"   # upload webui log with exit code
+      - name: assert success
+        run: |
+          if [ $(cat jest/frontend/jest.exit-code) != 0 ]; then cat jest/frontend/jest.log && exit 1; fi            # print frontend log and exit if frontend failed
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
@@ -379,9 +382,9 @@ jobs:
           docker run --rm --volume "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }}           # extracting java8 test results from docker image
           docker run --rm --volume "$(pwd)/junit:/reports" metasfresh/metas-junit:${{ needs.init.outputs.tag-fixed }}-j14       # extracting java14 test results from docker image
           find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;                                                           # upload all junit xml's to testspace 
-          testspace "[junit/commons]junit/commons/junit.log{$(cat junit/commons/junit.exit-code):java 8 commons junit tests}"   # upload commons log with exit code 
-          testspace "[junit/backend]junit/backend/junit.log{$(cat junit/backend/junit.exit-code):java 8 backend junit tests}"   # upload backend log with exit code
-          testspace "[junit/camel]junit/camel/junit.log{$(cat junit/camel/junit.exit-code):jav 14 camel junit tests}"           # upload camel log with exit code      
+          testspace "[junit/commons]junit/commons/junit.log{$(awk '{ sum += $1 } END { print sum }' junit/commons/junit.exit-code junit/commons/junit.mvn.exit-code):java 8 commons junit tests}"     # upload commons log with exit code 
+          testspace "[junit/backend]junit/backend/junit.log{$(awk '{ sum += $1 } END { print sum }' junit/backend/junit.exit-code junit/backend/junit.mvn.exit-code):java 8 backend junit tests}"     # upload backend log with exit code
+          testspace "[junit/camel]junit/camel/junit.log{$(awk '{ sum += $1 } END { print sum }' junit/camel/junit.exit-code junit/camel/junit.mvn.exit-code):java 14 camel junit tests}"              # upload camel log with exit code      
       - name: assert success
         run: |
           if [ $(cat junit/commons/junit.exit-code) != 0 ] || [ $(cat junit/commons/junit.mvn.exit-code) != 0 ]; then cat junit/commons/junit.log && exit 1; fi      # print commons log and exit if commons failed
